// <auto-generated />
using System;
using GestaodeReembolsos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestaodeReembolsos.Migrations
{
    [DbContext(typeof(GestaoDeReembolsoContext))]
    [Migration("20260813192021_AddRequestStatusHistories")]
    partial class AddRequestStatusHistories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestaodeReembolsos.Models.ApprovalDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Comment");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc")
                        .HasDefaultValueSql("(SYSUTCDATETIME())");

                    b.Property<Guid>("DecidedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Decision");

                    b.Property<string>("DecisionLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DecisionLevel");

                    b.Property<Guid>("ReimbursementRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DecidedByUserId");

                    b.HasIndex("ReimbursementRequestId");

                    b.ToTable("ApprovalDecisions", (string)null);
                });

            modelBuilder.Entity("GestaodeReembolsos.Models.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("CostCenterCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CostCenterCode");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc")
                        .HasDefaultValueSql("(SYSUTCDATETIME())");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("IsActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CostCenterCode" }, "IX_Department_CostCenterCode")
                        .IsUnique();

                    b.HasIndex(new[] { "Name" }, "IX_Department_Name")
                        .IsUnique();

                    b.ToTable("Departments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c3a3b4d8-28c3-4d72-a479-55c39a5bd101"),
                            CostCenterCode = "TI-100",
                            CreatedAtUtc = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Tecnologia"
                        },
                        new
                        {
                            Id = new Guid("6f468dfa-4cb8-46a9-a6fd-4e333787e202"),
                            CostCenterCode = "COM-200",
                            CreatedAtUtc = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Comercial"
                        },
                        new
                        {
                            Id = new Guid("e154d747-f905-4bea-a32d-13bcc991c303"),
                            CostCenterCode = "FIN-300",
                            CreatedAtUtc = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Financeiro"
                        });
                });

            modelBuilder.Entity("GestaodeReembolsos.Models.ExpenseCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("IsActive");

                    b.Property<decimal?>("MonthlyLimit")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("MonthlyLimit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("Name");

                    b.Property<bool>("RequiresReceipt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("RequiresReceipt");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "IX_ExpenseCategory_Name")
                        .IsUnique();

                    b.ToTable("ExpenseCategories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("1d7d9f1c-cba5-488d-a718-5102401ee001"),
                            IsActive = true,
                            MonthlyLimit = 800m,
                            Name = "Alimentação",
                            RequiresReceipt = true
                        },
                        new
                        {
                            Id = new Guid("413b783c-2030-40a8-8a09-a03ea12cd002"),
                            IsActive = true,
                            MonthlyLimit = 600m,
                            Name = "Transporte",
                            RequiresReceipt = true
                        },
                        new
                        {
                            Id = new Guid("59f8b4b9-e72b-4dbd-955b-cb67e940e003"),
                            IsActive = true,
                            MonthlyLimit = 3000m,
                            Name = "Hospedagem",
                            RequiresReceipt = true
                        },
                        new
                        {
                            Id = new Guid("f741aa00-84e1-4a02-a5e4-249268fee004"),
                            IsActive = true,
                            MonthlyLimit = 500m,
                            Name = "Material de escritório",
                            RequiresReceipt = true
                        },
                        new
                        {
                            Id = new Guid("a80f04df-615f-4f0c-8efc-44f39543f005"),
                            IsActive = true,
                            MonthlyLimit = 1000m,
                            Name = "Quilometragem",
                            RequiresReceipt = false
                        },
                        new
                        {
                            Id = new Guid("bff56b5b-29d8-40f4-8e32-f9a4590d3006"),
                            IsActive = true,
                            MonthlyLimit = 300m,
                            Name = "Outros",
                            RequiresReceipt = true
                        });
                });

            modelBuilder.Entity("GestaodeReembolsos.Models.ExpenseItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("Amount");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc")
                        .HasDefaultValueSql("(SYSUTCDATETIME())");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("Description");

                    b.Property<Guid>("ExpenseCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("ExpenseDate")
                        .HasColumnType("date")
                        .HasColumnName("ExpenseDate");

                    b.Property<string>("MerchantName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("MerchantName");

                    b.Property<string>("ReceiptFileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ReceiptFileName");

                    b.Property<string>("ReceiptStorageKey")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ReceiptStorageKey");

                    b.Property<Guid>("ReimbursementRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAtUtc");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseCategoryId");

                    b.HasIndex("ReimbursementRequestId");

                    b.ToTable("ExpenseItems", (string)null);
                });

            modelBuilder.Entity("GestaodeReembolsos.Models.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc")
                        .HasDefaultValueSql("(SYSUTCDATETIME())");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Notes");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("PaidAmount");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("date")
                        .HasColumnName("PaymentDate");

                    b.Property<string>("PaymentReference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("PaymentReference");

                    b.Property<Guid>("ProcessedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReimbursementRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PaymentReference")
                        .IsUnique();

                    b.HasIndex("ProcessedByUserId");

                    b.HasIndex("ReimbursementRequestId")
                        .IsUnique();

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("GestaodeReembolsos.Models.ReimbursementRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc")
                        .HasDefaultValueSql("(SYSUTCDATETIME())");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("FinanceDecisionAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("FinanceDecisionAtUtc");

                    b.Property<DateTime?>("ManagerDecisionAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("ManagerDecisionAtUtc");

                    b.Property<DateTime?>("PaidAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("PaidAtUtc");

                    b.Property<DateOnly>("ReferenceMonth")
                        .HasColumnType("date")
                        .HasColumnName("ReferenceMonth");

                    b.Property<string>("RequestNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("RequestNumber");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Status");

                    b.Property<DateTime?>("SubmittedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("SubmittedAtUtc");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("TotalAmount");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAtUtc");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("Version");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex(new[] { "RequestNumber" }, "IX_ReimbursementRequest_RequestNumber")
                        .IsUnique();

                    b.ToTable("ReimbursementRequests", (string)null);
                });

            modelBuilder.Entity("GestaodeReembolsos.Models.RequestStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChangedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc")
                        .HasDefaultValueSql("(SYSUTCDATETIME())");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NewStatus");

                    b.Property<string>("PreviousStatus")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PreviousStatus");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Reason");

                    b.Property<Guid>("ReimbursementRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("ReimbursementRequestId");

                    b.ToTable("RequestStatusHistories", (string)null);
                });

            modelBuilder.Entity("GestaodeReembolsos.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc")
                        .HasDefaultValueSql("(SYSUTCDATETIME())");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("FullName");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("IsActive");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PasswordHash");

                    b.Property<string>("RoleEnum")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Role");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAtUtc");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ManagerId");

                    b.HasIndex(new[] { "Email" }, "IX_User_Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9f586795-fc0f-4b35-b251-48cbab902401"),
                            CreatedAtUtc = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = new Guid("c3a3b4d8-28c3-4d72-a479-55c39a5bd101"),
                            Email = "carlos.lima@empresa.test",
                            FullName = "Carlos Lima",
                            IsActive = true,
                            PasswordHash = "$2y$10$GtYsJ4hK2nFZcmlVkht08uEg4/iiM.XuDj3oFODONcwxqeowXch4W",
                            RoleEnum = "Manager"
                        },
                        new
                        {
                            Id = new Guid("ad9bf52d-1a99-4f03-a64e-65aee12f2502"),
                            CreatedAtUtc = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = new Guid("6f468dfa-4cb8-46a9-a6fd-4e333787e202"),
                            Email = "marina.costa@empresa.test",
                            FullName = "Marina Costa",
                            IsActive = true,
                            PasswordHash = "$2y$10$GtYsJ4hK2nFZcmlVkht08uEg4/iiM.XuDj3oFODONcwxqeowXch4W",
                            RoleEnum = "Manager"
                        },
                        new
                        {
                            Id = new Guid("d62bdf0d-2268-4c5f-b6ef-d7d9f62d3603"),
                            CreatedAtUtc = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = new Guid("c3a3b4d8-28c3-4d72-a479-55c39a5bd101"),
                            Email = "ana.souza@empresa.test",
                            FullName = "Ana Souza",
                            IsActive = true,
                            ManagerId = new Guid("9f586795-fc0f-4b35-b251-48cbab902401"),
                            PasswordHash = "$2y$10$GtYsJ4hK2nFZcmlVkht08uEg4/iiM.XuDj3oFODONcwxqeowXch4W",
                            RoleEnum = "Employee"
                        },
                        new
                        {
                            Id = new Guid("fbb62499-5f39-4e04-98fe-5762a2c15704"),
                            CreatedAtUtc = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = new Guid("6f468dfa-4cb8-46a9-a6fd-4e333787e202"),
                            Email = "bruno.alves@empresa.test",
                            FullName = "Bruno Alves",
                            IsActive = true,
                            ManagerId = new Guid("ad9bf52d-1a99-4f03-a64e-65aee12f2502"),
                            PasswordHash = "$2y$10$GtYsJ4hK2nFZcmlVkht08uEg4/iiM.XuDj3oFODONcwxqeowXch4W",
                            RoleEnum = "Employee"
                        },
                        new
                        {
                            Id = new Guid("00bf84cc-22dc-401b-a1ec-a8d523687105"),
                            CreatedAtUtc = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = new Guid("e154d747-f905-4bea-a32d-13bcc991c303"),
                            Email = "fernanda.rocha@empresa.test",
                            FullName = "Fernanda Rocha",
                            IsActive = true,
                            PasswordHash = "$2y$10$GtYsJ4hK2nFZcmlVkht08uEg4/iiM.XuDj3oFODONcwxqeowXch4W",
                            RoleEnum = "Finance"
                        },
                        new
                        {
                            Id = new Guid("c95ab38b-5c3e-45a4-a087-c930bea18e06"),
                            CreatedAtUtc = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = new Guid("e154d747-f905-4bea-a32d-13bcc991c303"),
                            Email = "admin@empresa.test",
                            FullName = "Admin Sistema",
                            IsActive = true,
                            PasswordHash = "$2y$10$GtYsJ4hK2nFZcmlVkht08uEg4/iiM.XuDj3oFODONcwxqeowXch4W",
                            RoleEnum = "Admin"
                        });
                });

            modelBuilder.Entity("GestaodeReembolsos.Models.ApprovalDecision", b =>
                {
                    b.HasOne("GestaodeReembolsos.Models.User", "DecidedByUser")
                        .WithMany("ApprovalDecisions")
                        .HasForeignKey("DecidedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestaodeReembolsos.Models.ReimbursementRequest", "ReimbursementRequest")
                        .WithMany("ApprovalDecisions")
                        .HasForeignKey("ReimbursementRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DecidedByUser");

                    b.Navigation("ReimbursementRequest");
                });

            modelBuilder.Entity("GestaodeReembolsos.Models.ExpenseItem", b =>
                {
                    b.HasOne("GestaodeReembolsos.Models.ExpenseCategory", "ExpenseCategory")
                        .WithMany("ExpenseItems")
                        .HasForeignKey("ExpenseCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestaodeReembolsos.Models.ReimbursementRequest", "ReimbursementRequest")
                        .WithMany("ExpenseItems")
                        .HasForeignKey("ReimbursementRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExpenseCategory");

                    b.Navigation("ReimbursementRequest");
                });

            modelBuilder.Entity("GestaodeReembolsos.Models.Payment", b =>
                {
                    b.HasOne("GestaodeReembolsos.Models.User", "ProcessedByUser")
                        .WithMany("Payments")
                        .HasForeignKey("ProcessedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestaodeReembolsos.Models.ReimbursementRequest", "ReimbursementRequest")
                        .WithOne("Payment")
                        .HasForeignKey("GestaodeReembolsos.Models.Payment", "ReimbursementRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProcessedByUser");

                    b.Navigation("ReimbursementRequest");
                });

            modelBuilder.Entity("GestaodeReembolsos.Models.ReimbursementRequest", b =>
                {
                    b.HasOne("GestaodeReembolsos.Models.Department", "Department")
                        .WithMany("Requests")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestaodeReembolsos.Models.User", "Employee")
                        .WithMany("Requests")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("GestaodeReembolsos.Models.RequestStatusHistory", b =>
                {
                    b.HasOne("GestaodeReembolsos.Models.User", "ChangedByUser")
                        .WithMany("RequestStatusHistories")
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestaodeReembolsos.Models.ReimbursementRequest", "ReimbursementRequest")
                        .WithMany("RequestStatusHistories")
                        .HasForeignKey("ReimbursementRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("ReimbursementRequest");
                });

            modelBuilder.Entity("GestaodeReembolsos.Models.User", b =>
                {
                    b.HasOne("GestaodeReembolsos.Models.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestaodeReembolsos.Models.User", "Manager")
                        .WithMany("Subordinates")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("GestaodeReembolsos.Models.Department", b =>
                {
                    b.Navigation("Requests");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("GestaodeReembolsos.Models.ExpenseCategory", b =>
                {
                    b.Navigation("ExpenseItems");
                });

            modelBuilder.Entity("GestaodeReembolsos.Models.ReimbursementRequest", b =>
                {
                    b.Navigation("ApprovalDecisions");

                    b.Navigation("ExpenseItems");

                    b.Navigation("Payment");

                    b.Navigation("RequestStatusHistories");
                });

            modelBuilder.Entity("GestaodeReembolsos.Models.User", b =>
                {
                    b.Navigation("ApprovalDecisions");

                    b.Navigation("Payments");

                    b.Navigation("RequestStatusHistories");

                    b.Navigation("Requests");

                    b.Navigation("Subordinates");
                });
#pragma warning restore 612, 618
        }
    }
}
