// <auto-generated />
using System;
using GestaodeReembolsos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestaodeReembolsos.Migrations
{
    [DbContext(typeof(GestaoDeReembolsoContext))]
    [Migration("20260820194819_CriarBancoEmPortugues")]
    partial class CriarBancoEmPortugues
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestaodeReembolsos.Models.CategoriaDespesa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Ativo");

                    b.Property<bool>("ExigeComprovante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("ExigeComprovante");

                    b.Property<decimal?>("LimiteMensal")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("LimiteMensal");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "IX_ExpenseCategory_Name")
                        .IsUnique();

                    b.ToTable("CategoriasDespesa", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("1d7d9f1c-cba5-488d-a718-5102401ee001"),
                            Ativo = true,
                            ExigeComprovante = true,
                            LimiteMensal = 800m,
                            Name = "Alimentação"
                        },
                        new
                        {
                            Id = new Guid("413b783c-2030-40a8-8a09-a03ea12cd002"),
                            Ativo = true,
                            ExigeComprovante = true,
                            LimiteMensal = 600m,
                            Name = "Transporte"
                        },
                        new
                        {
                            Id = new Guid("59f8b4b9-e72b-4dbd-955b-cb67e940e003"),
                            Ativo = true,
                            ExigeComprovante = true,
                            LimiteMensal = 3000m,
                            Name = "Hospedagem"
                        },
                        new
                        {
                            Id = new Guid("f741aa00-84e1-4a02-a5e4-249268fee004"),
                            Ativo = true,
                            ExigeComprovante = true,
                            LimiteMensal = 500m,
                            Name = "Material de escritório"
                        },
                        new
                        {
                            Id = new Guid("a80f04df-615f-4f0c-8efc-44f39543f005"),
                            Ativo = true,
                            ExigeComprovante = false,
                            LimiteMensal = 1000m,
                            Name = "Quilometragem"
                        },
                        new
                        {
                            Id = new Guid("bff56b5b-29d8-40f4-8e32-f9a4590d3006"),
                            Ativo = true,
                            ExigeComprovante = true,
                            LimiteMensal = 300m,
                            Name = "Outros"
                        });
                });

            modelBuilder.Entity("GestaodeReembolsos.Models.DecisaoAprovacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comentario")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Comentario");

                    b.Property<DateTime>("CriadaEmUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CriadaEmUtc")
                        .HasDefaultValueSql("(SYSUTCDATETIME())");

                    b.Property<Guid>("DecididaPorUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Decisao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Decisao");

                    b.Property<string>("NivelDecisao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NivelDecisao");

                    b.Property<Guid>("SolicitacaoReembolsoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DecididaPorUsuarioId");

                    b.HasIndex("SolicitacaoReembolsoId");

                    b.ToTable("DecisoesAprovacao", (string)null);
                });

            modelBuilder.Entity("GestaodeReembolsos.Models.Departamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Ativo");

                    b.Property<string>("CodigoCentroCusto")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CodigoCentroCusto");

                    b.Property<DateTime>("CriadaEmUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CriadaEmUtc")
                        .HasDefaultValueSql("(SYSUTCDATETIME())");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CodigoCentroCusto" }, "IX_Department_CostCenterCode")
                        .IsUnique();

                    b.HasIndex(new[] { "Name" }, "IX_Department_Name")
                        .IsUnique();

                    b.ToTable("Departamentos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c3a3b4d8-28c3-4d72-a479-55c39a5bd101"),
                            Ativo = true,
                            CodigoCentroCusto = "TI-100",
                            CriadaEmUtc = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Tecnologia"
                        },
                        new
                        {
                            Id = new Guid("6f468dfa-4cb8-46a9-a6fd-4e333787e202"),
                            Ativo = true,
                            CodigoCentroCusto = "COM-200",
                            CriadaEmUtc = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Comercial"
                        },
                        new
                        {
                            Id = new Guid("e154d747-f905-4bea-a32d-13bcc991c303"),
                            Ativo = true,
                            CodigoCentroCusto = "FIN-300",
                            CriadaEmUtc = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Financeiro"
                        });
                });

            modelBuilder.Entity("GestaodeReembolsos.Models.HistoricoStatusSolicitacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AlteradoPorUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CriadaEmUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CriadaEmUtc")
                        .HasDefaultValueSql("(SYSUTCDATETIME())");

                    b.Property<string>("NovoStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NovoStatus");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Reason");

                    b.Property<Guid>("SolicitacaoReembolsoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StatusAnterior")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("StatusAnterior");

                    b.HasKey("Id");

                    b.HasIndex("AlteradoPorUsuarioId");

                    b.HasIndex("SolicitacaoReembolsoId");

                    b.ToTable("HistoricosStatusSolicitacao", (string)null);
                });

            modelBuilder.Entity("GestaodeReembolsos.Models.ItemDespesa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime?>("AtualizadaEmUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("AtualizadaEmUtc");

                    b.Property<Guid>("CategoriaDespesaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChaveArmazenamentoComprovante")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ChaveArmazenamentoComprovante");

                    b.Property<DateTime>("CriadaEmUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CriadaEmUtc")
                        .HasDefaultValueSql("(SYSUTCDATETIME())");

                    b.Property<DateOnly>("DataDespesa")
                        .HasColumnType("date")
                        .HasColumnName("DataDespesa");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("Descricao");

                    b.Property<string>("NomeArquivoComprovante")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("NomeArquivoComprovante");

                    b.Property<string>("NomeEstabelecimento")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("NomeEstabelecimento");

                    b.Property<Guid>("SolicitacaoReembolsoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("Valor");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaDespesaId");

                    b.HasIndex("SolicitacaoReembolsoId");

                    b.ToTable("ItensDespesa", (string)null);
                });

            modelBuilder.Entity("GestaodeReembolsos.Models.Pagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CriadaEmUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CriadaEmUtc")
                        .HasDefaultValueSql("(SYSUTCDATETIME())");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Observacoes");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("PaidAmount");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("date")
                        .HasColumnName("PaymentDate");

                    b.Property<Guid>("ProcessadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReferenciaPagamento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ReferenciaPagamento");

                    b.Property<Guid>("SolicitacaoReembolsoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProcessadoPorUsuarioId");

                    b.HasIndex("ReferenciaPagamento")
                        .IsUnique();

                    b.HasIndex("SolicitacaoReembolsoId")
                        .IsUnique();

                    b.ToTable("Pagamentos", (string)null);
                });

            modelBuilder.Entity("GestaodeReembolsos.Models.SolicitacaoReembolso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime?>("AtualizadaEmUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("AtualizadaEmUtc");

                    b.Property<Guid>("ColaboradorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CriadaEmUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CriadaEmUtc")
                        .HasDefaultValueSql("(SYSUTCDATETIME())");

                    b.Property<DateTime?>("DecididaPeloFinanceiroEmUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("DecididaPeloFinanceiroEmUtc");

                    b.Property<DateTime>("DecididaPeloGestorEmUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("DecididaPeloGestorEmUtc");

                    b.Property<Guid>("DepartamentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EnviadaEmUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("EnviadaEmUtc");

                    b.Property<DateOnly>("MesReferencia")
                        .HasColumnType("date")
                        .HasColumnName("MesReferencia");

                    b.Property<string>("NumeroSolicitacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("NumeroSolicitacao");

                    b.Property<DateTime?>("PagaEmUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("PagaEmUtc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Status");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("ValorTotal");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("Version");

                    b.HasKey("Id");

                    b.HasIndex("ColaboradorId");

                    b.HasIndex("DepartamentoId");

                    b.HasIndex(new[] { "NumeroSolicitacao" }, "IX_ReimbursementRequest_RequestNumber")
                        .IsUnique();

                    b.ToTable("SolicitacoesReembolso", (string)null);
                });

            modelBuilder.Entity("GestaodeReembolsos.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Ativo");

                    b.Property<DateTime?>("AtualizadaEmUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("AtualizadaEmUtc");

                    b.Property<DateTime>("CriadaEmUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CriadaEmUtc")
                        .HasDefaultValueSql("(SYSUTCDATETIME())");

                    b.Property<Guid>("DepartamentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Email");

                    b.Property<Guid?>("GestorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HashSenha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HashSenha");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("NomeCompleto");

                    b.Property<string>("PerfilUsuario")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Role");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentoId");

                    b.HasIndex("GestorId");

                    b.HasIndex(new[] { "Email" }, "IX_User_Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9f586795-fc0f-4b35-b251-48cbab902401"),
                            Ativo = true,
                            CriadaEmUtc = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartamentoId = new Guid("c3a3b4d8-28c3-4d72-a479-55c39a5bd101"),
                            Email = "carlos.lima@empresa.test",
                            HashSenha = "$2y$10$GtYsJ4hK2nFZcmlVkht08uEg4/iiM.XuDj3oFODONcwxqeowXch4W",
                            NomeCompleto = "Carlos Lima",
                            PerfilUsuario = "Manager"
                        },
                        new
                        {
                            Id = new Guid("ad9bf52d-1a99-4f03-a64e-65aee12f2502"),
                            Ativo = true,
                            CriadaEmUtc = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartamentoId = new Guid("6f468dfa-4cb8-46a9-a6fd-4e333787e202"),
                            Email = "marina.costa@empresa.test",
                            HashSenha = "$2y$10$GtYsJ4hK2nFZcmlVkht08uEg4/iiM.XuDj3oFODONcwxqeowXch4W",
                            NomeCompleto = "Marina Costa",
                            PerfilUsuario = "Manager"
                        },
                        new
                        {
                            Id = new Guid("d62bdf0d-2268-4c5f-b6ef-d7d9f62d3603"),
                            Ativo = true,
                            CriadaEmUtc = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartamentoId = new Guid("c3a3b4d8-28c3-4d72-a479-55c39a5bd101"),
                            Email = "ana.souza@empresa.test",
                            GestorId = new Guid("9f586795-fc0f-4b35-b251-48cbab902401"),
                            HashSenha = "$2y$10$GtYsJ4hK2nFZcmlVkht08uEg4/iiM.XuDj3oFODONcwxqeowXch4W",
                            NomeCompleto = "Ana Souza",
                            PerfilUsuario = "Employee"
                        },
                        new
                        {
                            Id = new Guid("fbb62499-5f39-4e04-98fe-5762a2c15704"),
                            Ativo = true,
                            CriadaEmUtc = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartamentoId = new Guid("6f468dfa-4cb8-46a9-a6fd-4e333787e202"),
                            Email = "bruno.alves@empresa.test",
                            GestorId = new Guid("ad9bf52d-1a99-4f03-a64e-65aee12f2502"),
                            HashSenha = "$2y$10$GtYsJ4hK2nFZcmlVkht08uEg4/iiM.XuDj3oFODONcwxqeowXch4W",
                            NomeCompleto = "Bruno Alves",
                            PerfilUsuario = "Employee"
                        },
                        new
                        {
                            Id = new Guid("00bf84cc-22dc-401b-a1ec-a8d523687105"),
                            Ativo = true,
                            CriadaEmUtc = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartamentoId = new Guid("e154d747-f905-4bea-a32d-13bcc991c303"),
                            Email = "fernanda.rocha@empresa.test",
                            HashSenha = "$2y$10$GtYsJ4hK2nFZcmlVkht08uEg4/iiM.XuDj3oFODONcwxqeowXch4W",
                            NomeCompleto = "Fernanda Rocha",
                            PerfilUsuario = "Finance"
                        },
                        new
                        {
                            Id = new Guid("c95ab38b-5c3e-45a4-a087-c930bea18e06"),
                            Ativo = true,
                            CriadaEmUtc = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartamentoId = new Guid("e154d747-f905-4bea-a32d-13bcc991c303"),
                            Email = "admin@empresa.test",
                            HashSenha = "$2y$10$GtYsJ4hK2nFZcmlVkht08uEg4/iiM.XuDj3oFODONcwxqeowXch4W",
                            NomeCompleto = "Admin Sistema",
                            PerfilUsuario = "Admin"
                        });
                });

            modelBuilder.Entity("GestaodeReembolsos.Models.DecisaoAprovacao", b =>
                {
                    b.HasOne("GestaodeReembolsos.Models.Usuario", "DecidedByUser")
                        .WithMany("DecisoesAprovacao")
                        .HasForeignKey("DecididaPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestaodeReembolsos.Models.SolicitacaoReembolso", "SolicitacaoReembolso")
                        .WithMany("DecisoesAprovacao")
                        .HasForeignKey("SolicitacaoReembolsoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DecidedByUser");

                    b.Navigation("SolicitacaoReembolso");
                });

            modelBuilder.Entity("GestaodeReembolsos.Models.HistoricoStatusSolicitacao", b =>
                {
                    b.HasOne("GestaodeReembolsos.Models.Usuario", "ChangedByUser")
                        .WithMany("HistoricosStatusSolicitacao")
                        .HasForeignKey("AlteradoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestaodeReembolsos.Models.SolicitacaoReembolso", "SolicitacaoReembolso")
                        .WithMany("HistoricosStatusSolicitacao")
                        .HasForeignKey("SolicitacaoReembolsoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("SolicitacaoReembolso");
                });

            modelBuilder.Entity("GestaodeReembolsos.Models.ItemDespesa", b =>
                {
                    b.HasOne("GestaodeReembolsos.Models.CategoriaDespesa", "CategoriaDespesa")
                        .WithMany("ItensDespesa")
                        .HasForeignKey("CategoriaDespesaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestaodeReembolsos.Models.SolicitacaoReembolso", "SolicitacaoReembolso")
                        .WithMany("ItensDespesa")
                        .HasForeignKey("SolicitacaoReembolsoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CategoriaDespesa");

                    b.Navigation("SolicitacaoReembolso");
                });

            modelBuilder.Entity("GestaodeReembolsos.Models.Pagamento", b =>
                {
                    b.HasOne("GestaodeReembolsos.Models.Usuario", "ProcessedByUser")
                        .WithMany("Pagamentos")
                        .HasForeignKey("ProcessadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestaodeReembolsos.Models.SolicitacaoReembolso", "SolicitacaoReembolso")
                        .WithOne("Pagamento")
                        .HasForeignKey("GestaodeReembolsos.Models.Pagamento", "SolicitacaoReembolsoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProcessedByUser");

                    b.Navigation("SolicitacaoReembolso");
                });

            modelBuilder.Entity("GestaodeReembolsos.Models.SolicitacaoReembolso", b =>
                {
                    b.HasOne("GestaodeReembolsos.Models.Usuario", "Employee")
                        .WithMany("Requests")
                        .HasForeignKey("ColaboradorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestaodeReembolsos.Models.Departamento", "Departamento")
                        .WithMany("Requests")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Departamento");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("GestaodeReembolsos.Models.Usuario", b =>
                {
                    b.HasOne("GestaodeReembolsos.Models.Departamento", "Departamento")
                        .WithMany("Usuarios")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestaodeReembolsos.Models.Usuario", "Manager")
                        .WithMany("Subordinados")
                        .HasForeignKey("GestorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Departamento");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("GestaodeReembolsos.Models.CategoriaDespesa", b =>
                {
                    b.Navigation("ItensDespesa");
                });

            modelBuilder.Entity("GestaodeReembolsos.Models.Departamento", b =>
                {
                    b.Navigation("Requests");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("GestaodeReembolsos.Models.SolicitacaoReembolso", b =>
                {
                    b.Navigation("DecisoesAprovacao");

                    b.Navigation("HistoricosStatusSolicitacao");

                    b.Navigation("ItensDespesa");

                    b.Navigation("Pagamento");
                });

            modelBuilder.Entity("GestaodeReembolsos.Models.Usuario", b =>
                {
                    b.Navigation("DecisoesAprovacao");

                    b.Navigation("HistoricosStatusSolicitacao");

                    b.Navigation("Pagamentos");

                    b.Navigation("Requests");

                    b.Navigation("Subordinados");
                });
#pragma warning restore 612, 618
        }
    }
}
